// Structured output support inspired by Apple's @Generable pattern.
//
// In Apple's FoundationModels framework, @Generable types can be directly
// generated by the model with compile-time schema derivation. We bring a
// similar idea to the multi-provider world: conforming types describe their
// JSON Schema, and the framework wraps the schema in the system prompt or
// tool call as needed for each provider.
//
// For types that are also Codable, we can automatically deserialize the
// model's JSON output into the Swift type.

import Foundation

/// A type that can be generated by a language model via structured output.
///
/// Inspired by Apple's `@Generable` macro. Conforming types provide a JSON
/// Schema that constrains the model's output, and optionally custom guidance
/// (similar to Apple's `@Guide` property wrapper).
///
/// Usage:
/// ```swift
/// struct MovieReview: Generable, Codable {
///     static var schema: JSONSchema {
///         .object(properties: [
///             "title": .string(description: "Movie title"),
///             "rating": .integer(description: "Rating from 1 to 5"),
///             "summary": .string(description: "Brief review"),
///         ], required: ["title", "rating", "summary"])
///     }
///
///     let title: String
///     let rating: Int
///     let summary: String
/// }
///
/// let review: MovieReview = try await piAI.generate(
///     model: model,
///     prompt: "Review the movie Inception"
/// )
/// ```
public protocol Generable: Sendable {
    /// JSON Schema describing the expected structure.
    static var schema: JSONSchema { get }

    /// Optional instruction text appended to the system prompt to guide
    /// the model's output format. Defaults to a standard JSON instruction.
    static var generationGuidance: String { get }
}

extension Generable {
    public static var generationGuidance: String {
        "Respond with valid JSON matching the provided schema. Do not include markdown formatting or code blocks."
    }
}

/// A structured output request that wraps a Generable type with a prompt.
public struct GenerateRequest<T: Generable & Decodable>: Sendable {
    public let prompt: String
    public let systemPrompt: String?

    public init(prompt: String, systemPrompt: String? = nil) {
        self.prompt = prompt
        self.systemPrompt = systemPrompt
    }

    /// Build the context with schema instructions baked into the system prompt.
    public func buildContext() -> Context {
        let schemaJSON = T.schema.toJSON()
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]

        var schemaText = "{}" // fallback
        if let data = try? encoder.encode(schemaJSON),
           let str = String(data: data, encoding: .utf8)
        {
            schemaText = str
        }

        let systemInstruction = [
            systemPrompt,
            T.generationGuidance,
            "Output JSON Schema:\n\(schemaText)",
        ]
        .compactMap { $0 }
        .joined(separator: "\n\n")

        return Context(
            systemPrompt: systemInstruction,
            messages: [.user(UserMessage(prompt))]
        )
    }
}

/// Errors specific to structured output generation.
public enum GenerationError: Error, Sendable {
    case modelReturnedNoText
    case jsonDecodingFailed(String, Error)
    case modelError(String)
}

/// Generate a structured output from a model response.
///
/// Extracts the text from an `AssistantMessage` and decodes it as `T`.
public func decodeGenerated<T: Generable & Decodable>(
    _ type: T.Type,
    from message: AssistantMessage
) throws -> T {
    let text = message.text.trimmingCharacters(in: .whitespacesAndNewlines)
    guard !text.isEmpty else {
        throw GenerationError.modelReturnedNoText
    }

    if let errorMessage = message.errorMessage {
        throw GenerationError.modelError(errorMessage)
    }

    // Strip markdown code fences if the model wrapped its output
    let cleaned = stripCodeFences(text)

    guard let data = cleaned.data(using: .utf8) else {
        throw GenerationError.jsonDecodingFailed(cleaned, NSError(domain: "PiAI", code: -1))
    }

    do {
        return try JSONDecoder().decode(T.self, from: data)
    } catch {
        throw GenerationError.jsonDecodingFailed(cleaned, error)
    }
}

private func stripCodeFences(_ text: String) -> String {
    var result = text
    // Remove ```json ... ``` wrapping
    if result.hasPrefix("```json") {
        result = String(result.dropFirst(7))
    } else if result.hasPrefix("```") {
        result = String(result.dropFirst(3))
    }
    if result.hasSuffix("```") {
        result = String(result.dropLast(3))
    }
    return result.trimmingCharacters(in: .whitespacesAndNewlines)
}
